name: ADR Index with GPG Signing
on:
  push:
    paths:
      - 'ADRs/**.md'
      - '.github/workflows/adr-index-with-signing.yml'
  pull_request:
    paths:
      - 'ADRs/**.md'

jobs:
  adr-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push commits
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper git operations
          fetch-depth: 0

      - name: Install adrctl
        run: |
          curl -L https://github.com/alexlovelltroy/adrctl/releases/latest/download/adrctl_0.1.0_Linux_x86_64.tar.gz | tar xz
          sudo mv adrctl /usr/local/bin/

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Generate ADR index
        run: adrctl index --project-name "${{ github.event.repository.name }}" --project-url "${{ github.event.repository.html_url }}"

      - name: Check for changes
        id: changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add ADRs/index.md
          git commit -m "chore(adr): update index

          Automatically generated by GitHub Actions
          
          Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          git push

      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request' && steps.changes.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 ADR index has been automatically updated due to changes in ADR files.'
            })